

dist: trusty
sudo: false

addons:
  sonarcloud:
    organization: "cdadt"
    token:
      secure: 905f5eba405b0bafc9adf9f2026d30a3943f2052 # encrypted value of your token

language: node_js
node_js:
  - "10"

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - ls -al
  - npm run test
  - sonar-scanner
